import { StyleSheet } from "react-native";
export const ProfileStyle = StyleSheet.create({
    container: {
      flex: 1,
    },
    profileContainer: {
      justifyContent: 'flex-start',
      backgroundColor: '#F7F7F7',
      height: '100%',
      width: '100%',
      alignItems: 'flex-start',
      display: 'flex',
      position: 'relative',
      padding: 20,
      gap: 20,
    },
    loader: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    userInfo: {
      position: 'relative',
      borderWidth: 1,
      width: '100%',
      borderRadius: 15,
      gap: 10,
      backgroundColor: '#260094',
      padding: 15,
      alignItems: 'center', 
      flexDirection: 'row',
      justifyContent: 'space-between', 
      marginVertical: 10,
      shadowColor: '#000',
      shadowOffset: { width: 2, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
    },
    userData: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'flex-end',
      gap: 5, 
    },
    username: {
      fontSize: 20,
      color: '#fff',
      fontWeight: 'bold',
    },
    role: {
      fontSize: 18,
      color: '#fff',
    },
    sbjctList: {
      width: '100%',
      borderWidth: 1,
      backgroundColor: '#260094',
      borderRadius: 30,
      padding: 20,
      maxHeight: 300,
      shadowColor: '#000',
      shadowOffset: { width: 2, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
    },
    title: {
      fontSize: 24,
      fontWeight: 'bold',
      marginBottom: 10,
      color: '#fff',
    },
    productItem: {
      display: 'flex',
      padding: 10,
      borderWidth: 1,
      width: '100%',
      alignItems: 'flex-start',
      marginBottom: 10,
      backgroundColor: '#fff',
      borderRadius: 15,
      position: 'relative',
      top: 10,
    },
    course: {
      fontSize: 16,
      color: '#260094',
      fontWeight: 'bold',
    },
    button: {
      position: 'absolute',
      alignSelf: 'center',
      bottom: 20,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#6200ee',
      paddingVertical: 15,
      paddingHorizontal: 30,
      borderRadius: 25,
    },
    buttonText: {
      color: '#fff',
      fontSize: 18,
      fontWeight: 'bold',
    },
  });
  
